const SUCCESS = 200
const CREATED = 201
const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const NOT_FOUND = 404
const INTERNAL_SERVER = 500

module.exports = {
  SUCCESS,
  CREATED,
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER,
  UNAUTHORIZED
}
